/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GetConfig */
    get: operations['ApiConfigGetConfig'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/fix-font': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** FixFont */
    post: operations['ApiFixFontFixFont'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/font-theme': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** FontTheme */
    post: operations['ApiFontThemeFontTheme'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/font-theme/install': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** InstallFontThemeHandler */
    post: operations['ApiFontThemeInstallInstallFontThemeHandler'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/monospace-fonts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ListMonospaceFonts */
    get: operations['ApiMonospaceFontsListMonospaceFonts'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/themes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** ListThemes */
    get: operations['ApiThemesListThemes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AppConfig */
    AppConfig: {
      local: boolean;
      maxUploadSize: number;
    };
    /** BundledThemeInfo */
    BundledThemeInfo: {
      id: string;
      name: string;
      theme: components['schemas']['ThemeData'];
    };
    /** FixFontForm */
    FixFontForm: {
      /** Format: binary */
      file: string;
      /** @description The theme definition (ThemeData) encoded as JSON. */
      theme: string;
    };
    /** FixFontResult */
    FixFontResult: {
      /** Format: binary */
      file: string;
      /** @description The suggested file name of the fixed pptx file. */
      filename: string;
      log: string;
    };
    /** FontSet */
    FontSet: {
      hangul: string;
      latin: string;
      symbol: string;
    };
    /** FontThemeRequest */
    FontThemeRequest: {
      name: string;
      theme: components['schemas']['ThemeData'];
    };
    /** InstallFontThemeRequest */
    InstallFontThemeRequest: {
      name: string;
      /** @default false */
      overwrite: boolean;
      theme: components['schemas']['ThemeData'];
    };
    /** InstallFontThemeResult */
    InstallFontThemeResult: {
      path: string;
    };
    /** MonoFontSet */
    MonoFontSet: {
      hangul: string;
      latin: string;
    };
    /** ThemeData */
    ThemeData: {
      majorFont: components['schemas']['FontSet'];
      minorFont: components['schemas']['FontSet'];
      monoFont: components['schemas']['MonoFontSet'];
      options: components['schemas']['ThemeOptions'];
    };
    /** ThemeOptions */
    ThemeOptions: {
      bodyFirstLevelStyle: string | null;
      /** @default false */
      preserveMono: boolean;
      titleBold: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ApiConfigGetConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AppConfig'];
        };
      };
    };
  };
  ApiFixFontFixFont: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['FixFontForm'];
      };
    };
    responses: {
      /** @description The fixed pptx file with its suggested name and the processing log. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'multipart/form-data': components['schemas']['FixFontResult'];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  ApiFontThemeFontTheme: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FontThemeRequest'];
      };
    };
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/xml': string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  ApiFontThemeInstallInstallFontThemeHandler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InstallFontThemeRequest'];
      };
    };
    responses: {
      /** @description Document created, URL follows */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstallFontThemeResult'];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
            status_code: number;
          };
        };
      };
    };
  };
  ApiMonospaceFontsListMonospaceFonts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
    };
  };
  ApiThemesListThemes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BundledThemeInfo'][];
        };
      };
    };
  };
}
